# Generated by Django 2.2 on 2021-06-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCRM_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg', upload_to='images'),
            preserve_default=False,
        ),
    ]
